
package net.atos.weatherapplication.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OpenWeatherPortType", targetNamespace = "http://atos.net/weather_soap")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OpenWeatherPortType {


    /**
     * 
     * @param getWeather
     */
    @WebMethod(action = "/getWeather")
    @RequestWrapper(localName = "getWeather", targetNamespace = "http://atos.net/weather_soap", className = "net.atos.weatherapplication.soap.GetWeather")
    @ResponseWrapper(localName = "getWeather", targetNamespace = "http://atos.net/weather_soap", className = "net.atos.weatherapplication.soap.GetWeather")
    public void getWeather(
        @WebParam(name = "getWeather", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<String> getWeather);

}
