
package net.atos.weatherapplication.soap;

import org.springframework.stereotype.Component;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OpenWeatherService", targetNamespace = "http://atos.net/weather_soap", wsdlLocation = "file:/C:/Users/Adels/Desktop/net.atos.weatherapplication/src/main/resources/open_weather.wsdl")

public class OpenWeatherService
    extends Service
{

    private final static URL OPENWEATHERSERVICE_WSDL_LOCATION;
    private final static WebServiceException OPENWEATHERSERVICE_EXCEPTION;
    private final static QName OPENWEATHERSERVICE_QNAME = new QName("http://atos.net/weather_soap", "OpenWeatherService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Adels/Desktop/net.atos.weatherapplication/src/main/resources/open_weather.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OPENWEATHERSERVICE_WSDL_LOCATION = url;
        OPENWEATHERSERVICE_EXCEPTION = e;
    }

    public OpenWeatherService() {
        super(__getWsdlLocation(), OPENWEATHERSERVICE_QNAME);
    }

    public OpenWeatherService(WebServiceFeature... features) {
        super(__getWsdlLocation(), OPENWEATHERSERVICE_QNAME, features);
    }

    public OpenWeatherService(URL wsdlLocation) {
        super(wsdlLocation, OPENWEATHERSERVICE_QNAME);
    }

    public OpenWeatherService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OPENWEATHERSERVICE_QNAME, features);
    }

    public OpenWeatherService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OpenWeatherService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OpenWeatherPortType
     */
    @WebEndpoint(name = "OpenWeatherServiceSOAP")
    public OpenWeatherPortType getOpenWeatherServiceSOAP() {
        return super.getPort(new QName("http://atos.net/weather_soap", "OpenWeatherServiceSOAP"), OpenWeatherPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OpenWeatherPortType
     */
    @WebEndpoint(name = "OpenWeatherServiceSOAP")
    public OpenWeatherPortType getOpenWeatherServiceSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://atos.net/weather_soap", "OpenWeatherServiceSOAP"), OpenWeatherPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OPENWEATHERSERVICE_EXCEPTION!= null) {
            throw OPENWEATHERSERVICE_EXCEPTION;
        }
        return OPENWEATHERSERVICE_WSDL_LOCATION;
    }

}
